name: C++ Build, Run & Format Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ clang-format

      # 🔹 Step 1: Auto-format all C++ files
      - name: Auto-format C++ files
        run: |
          echo "Auto-formatting files..."
          find "Binary Seach" -name "*.cpp" -exec clang-format -i {} \;
          echo "Formatting complete."

      # 🔹 Step 2: Fail if formatting changes are needed
      - name: Verify formatting
        run: |
          echo "Checking formatting..."
          if ! git diff --exit-code; then
            echo "❌ Code was not properly formatted. Please run clang-format."
            exit 1
          else
            echo "✅ Formatting is correct."
          fi

      # 🔹 Step 3: Compile and run files (with test case check if .in/.out exist)
      - name: Compile and Run C++ Files
        run: |
          for file in Binary\ Seach/*.cpp; do
            if grep -q "int main" "$file"; then
              name=$(basename "$file" .cpp)
              echo "Compiling $file..."
              g++ "$file" -o program
              echo "Running $file..."
              if [[ -f "Binary Seach/$name.in" && -f "Binary Seach/$name.out" ]]; then
                ./program < "Binary Seach/$name.in" > result.txt
                if diff -q result.txt "Binary Seach/$name.out"; then
                  echo "✅ $name passed test"
                else
                  echo "❌ $name failed test"
                  exit 1
                fi
              else
                ./program || true
              fi
              echo "--------------------------------------"
            else
              echo "Skipping $file (no main function)"
            fi
          done
