name: C++ Build and Run

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install g++
        run: sudo apt-get install -y g++

      - name: Compile and Run C++ Files
        run: |
          for file in Binary\ Seach/*.cpp; do
            if grep -q "int main" "$file"; then
              echo "Compiling $file..."
              g++ "$file" -o program
              echo "Running $file..."
              ./program || true
              echo "--------------------------------------"
            else
              echo "Skipping $file (no main function)"
            fi
          done
