name: C++ Build and Run

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install g++
        run: sudo apt-get install -y g++

      - name: Compile and Run C++ Files
        run: |
          for file in Binary\ Seach/*.cpp; do
            echo "Compiling $file..."
            g++ "$file" -o program
            echo "Running $file..."
            ./program || true   # run program, don't fail workflow if exit code != 0
            echo "--------------------------------------"
          done
